-- SCRIPT PARTE 1 - CRIACAO DO BANCO
-- Execute esta parte conectado a um banco administrativo, como postgres.
-- Se o banco ja existir, o bloco nao cria novamente.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_database
        WHERE datname = 'ordem_servico_mvc'
    ) THEN
        EXECUTE 'CREATE DATABASE ordem_servico_mvc';
    END IF;
END
$$;

-- SCRIPT PARTE 2 - ESTRUTURA DO BANCO
-- Depois de executar a Parte 1, conecte-se ao banco ordem_servico_mvc
-- no DBeaver e execute o restante deste arquivo a partir daqui.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.clientes (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        varchar(150) NOT NULL,
    telefone    varchar(20),
    email       varchar(150),
    criado_em   timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_clientes_nome_nao_vazio
        CHECK (btrim(nome) <> ''),
    CONSTRAINT ck_clientes_email_tamanho
        CHECK (email IS NULL OR char_length(email) <= 150),
    CONSTRAINT ck_clientes_telefone_tamanho
        CHECK (telefone IS NULL OR char_length(telefone) <= 20)
);

CREATE INDEX IF NOT EXISTS ix_clientes_nome
    ON public.clientes (nome);

CREATE INDEX IF NOT EXISTS ix_clientes_email
    ON public.clientes (email);

CREATE INDEX IF NOT EXISTS ix_clientes_nome_trgm
    ON public.clientes
    USING gin (nome gin_trgm_ops);

CREATE INDEX IF NOT EXISTS ix_clientes_telefone_trgm
    ON public.clientes
    USING gin (telefone gin_trgm_ops);

CREATE INDEX IF NOT EXISTS ix_clientes_email_trgm
    ON public.clientes
    USING gin (email gin_trgm_ops);

COMMENT ON TABLE public.clientes IS 'Cadastro de clientes usado pelo projeto OrdemServicoMvc.';
COMMENT ON COLUMN public.clientes.id IS 'Identificador do cliente.';
COMMENT ON COLUMN public.clientes.nome IS 'Nome do cliente.';
COMMENT ON COLUMN public.clientes.telefone IS 'Telefone do cliente.';
COMMENT ON COLUMN public.clientes.email IS 'Email do cliente.';
COMMENT ON COLUMN public.clientes.criado_em IS 'Data de criacao do registro.';
